import React, { useEffect, useState } from 'react';
import { get, post } from '../services/api';
import { Message, Conversation } from '../types';
import { ToastState } from '../components/Toast';

function Empty({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><span className="empty-icon">◇</span><h3>{title}</h3><p>{text}</p>{action && <button className="primary" onClick={onAction}>{action}</button>}</div>; }
export function Conversations({ conversations, notify }: { conversations: Conversation[]; notify: (t: ToastState) => void }) {
  const [list, setList] = useState<Conversation[]>(conversations); const [selected, setSelected] = useState<Conversation>(); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setList(conversations); if (selected) setSelected(conversations.find(x => x.id === selected.id)); }, [conversations]);
  useEffect(() => { if (!selected) return; setLoading(true); setError(''); get<any>(`/api/conversations/${selected.id}/messages`).then(x => setMessages(x.data)).catch((e: any) => { setError(e.message || 'Não foi possível carregar as mensagens'); notify({ kind: 'error', title: 'Conversa indisponível', description: e.message }); }).finally(() => setLoading(false)); }, [selected, notify]);
  const send = async (simulate: boolean) => { if (!selected || !text.trim()) return; setBusy(true); try { const d: any = await post(`/api/conversations/${selected.id}/${simulate ? 'simulate-inbound' : 'messages'}`, simulate ? { text } : { text, idempotencyKey: `ui:${Date.now()}` }); setMessages(x => [...x, d.data]); setList(x => x.map(item => item.id === selected.id ? { ...item, lastMessage: d.data } : item)); setText(''); notify({ kind: 'success', title: simulate ? 'Mensagem recebida em SIMULAÇÃO' : 'Mensagem de teste enfileirada' }); } catch (e: any) { notify({ kind: 'error', title: 'Mensagem não enviada', description: e.message }); } finally { setBusy(false); } };
  return <section className="inbox"><div className="inbox-list panel"><h2>Conversas ({list.length})</h2>{list.map(c => <button className={`conversation-row ${selected?.id === c.id ? 'selected' : ''}`} onClick={() => setSelected(c)} key={c.id}><b>{c.lead.name}</b><span>{c.lead.company || 'Sem empresa'}</span><small>{c.lastMessage?.content || 'Nenhuma mensagem ainda'}</small><small>{c.lastMessage ? new Date(c.lastMessage.createdAt).toLocaleTimeString('pt-BR') : '—'} · {c.lead.status}</small></button>)}{!list.length && <Empty title="Nenhuma conversa ainda" text="Quando um contato responder, aparecerá aqui." />}</div><div className="chat panel">{selected ? <><div className="chat-head"><div><h2>{selected.lead.name}</h2><span className="muted">{selected.lead.phone}</span></div><span className="badge">SIMULAÇÃO</span></div>{loading && <div className="loading-state">Carregando mensagens…</div>}{error && <div className="error-state"><p>{error}</p><button className="ghost" onClick={() => setSelected({ ...selected })}>Tentar novamente</button></div>} {!loading && !error && <div className="messages">{messages.map(m => <div className={`message ${m.direction.toLowerCase()}`} key={m.id}><span>{m.content}</span><small>{m.status} · {new Date(m.createdAt).toLocaleTimeString('pt-BR')}</small></div>)}{!messages.length && <Empty title="Sem mensagens" text="Use a simulação para testar o fluxo de entrada." />}</div>}<div className="composer"><textarea value={text} onChange={e => setText(e.target.value)} placeholder="Mensagem de teste…"/><button className="ghost" disabled={busy || loading} onClick={() => send(true)}>Simular recebida</button><button className="primary" disabled={busy || loading} onClick={() => send(false)}>{busy ? 'Enviando…' : 'Enviar teste'}</button></div></> : <Empty title="Selecione uma conversa" text="Escolha um contato à esquerda para abrir a inbox." />}</div><div className="panel contact-card"><span className="eyebrow">CONTATO</span>{selected ? <><h2>{selected.lead.name}</h2><p>{selected.lead.company || 'Sem empresa'}</p><b>{selected.lead.consentStatus} · {selected.lead.status}</b><p className="muted">{selected.lead.phone} · {selected.lead.city || 'Cidade não informada'} · {selected.lead.niche || 'Nicho não informado'}</p><p className="muted">Instagram: {selected.lead.instagram || 'Não informado'} · Site: {selected.lead.site || 'Não informado'}</p><p className="muted">Responsável: {selected.lead.assignedUserId || 'Não atribuído'}</p></> : <p className="muted">Informações do contato</p>}</div></section>;
}



