import React, { useCallback, useEffect, useState } from 'react';
import { get, post } from '../services/api';
import { Modal, ToastState } from '../components/Toast';

const tabs = ['WhatsApp', 'Envio', 'Segurança', 'Usuários', 'Sistema'];
export function Settings({ notify }: { notify: (t: ToastState) => void }) {
  const [d, setD] = useState<any>(); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [confirmPause, setConfirmPause] = useState(false); const [active, setActive] = useState('WhatsApp');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setD(await get('/api/settings/whatsapp')); } catch (e: any) { setError(e.message || 'Erro inesperado'); notify({ kind: 'error', title: 'Configurações indisponíveis', description: e.message }); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { load(); }, [load]);
  const test = async () => { setBusy(true); try { const x: any = await post('/api/settings/whatsapp/test'); notify({ kind: x.ok ? 'success' : 'error', title: x.ok ? 'Conexão validada' : 'Falha na conexão', description: x.ok ? 'Provider respondeu em SIMULAÇÃO' : x.error }); } catch (e: any) { notify({ kind: 'error', title: 'Teste falhou', description: e.message }); } finally { setBusy(false); } };
  const change = async (paused: boolean) => { setBusy(true); try { await post(`/api/settings/${paused ? 'pause' : 'resume'}`, paused ? undefined : { confirm: true }); setD({ ...d, queuePaused: paused }); notify({ kind: paused ? 'warning' : 'success', title: paused ? 'ENVIOS PAUSADOS' : 'Envios reativados' }); } catch (e: any) { notify({ kind: 'error', title: 'Ação não concluída', description: e.message }); } finally { setBusy(false); } };
  if (loading) return <div className="panel loading-state">Carregando configurações…</div>;
  if (error) return <div className="panel error-state"><h3>Não foi possível carregar as configurações</h3><p>{error}</p><button className="primary" onClick={load}>Tentar novamente</button></div>;
  return <><div className="settings-tabs" role="tablist">{tabs.map(tab => <button key={tab} role="tab" aria-selected={active === tab} className={active === tab ? 'selected' : ''} onClick={() => setActive(tab)}>{tab}</button>)}</div>
    {active === 'WhatsApp' && <section className="settings-grid"><section className="panel setting-card"><span className="eyebrow">PROVIDER OFICIAL</span><h2>Meta WhatsApp Cloud API</h2><span className="badge">{d?.testMode ? 'SIMULAÇÃO · TEST_MODE' : 'REAL'}</span><p className="muted">Secrets não são exibidos. Nenhuma mensagem real será enviada em TEST_MODE.</p><div className="detail-grid"><div><small>WABA ID</small><b>Configurado no servidor</b></div><div><small>PHONE NUMBER ID</small><b>Configurado no servidor</b></div><div><small>WEBHOOK</small><b>/webhooks/whatsapp</b></div><div><small>ÚLTIMO EVENTO</small><b>{d?.lastEvent || 'Nenhum'}</b></div></div><button className="primary" disabled={busy} onClick={test}>{busy ? 'Testando conexão…' : 'Testar conexão'}</button></section><section className="panel setting-card"><span className="eyebrow">CONTROLE OPERACIONAL</span><h2>Envios e segurança</h2><p className={d?.queuePaused ? 'status-warn' : 'status-ok'}>{d?.queuePaused ? 'ENVIOS PAUSADOS' : 'Fila operacional'}</p><button disabled={busy} className={d?.queuePaused ? 'primary' : 'danger'} onClick={() => d?.queuePaused ? change(false) : setConfirmPause(true)}>{d?.queuePaused ? 'Reativar envios' : 'Pausar todos os envios'}</button></section></section>}
    {active === 'Envio' && <section className="panel setting-card"><span className="eyebrow">FILA E ESTABILIDADE</span><h2>Envio controlado</h2><p className="muted">BullMQ administra concorrência, retries com backoff, idempotência e circuit breaker.</p><p className={d?.queuePaused ? 'status-warn' : 'status-ok'}>{d?.queuePaused ? 'Envios pausados preventivamente' : 'Fila operacional'}</p></section>}
    {active === 'Segurança' && <section className="panel setting-card"><span className="eyebrow">PROTEÇÕES ATIVAS</span><h2>Segurança da operação</h2><p className="muted">CSRF, CORS restritivo, validação de payload, RBAC e Official API Guard protegem as rotas de envio.</p></section>}
    {active === 'Usuários' && <section className="panel setting-card"><span className="eyebrow">ACESSO</span><h2>Perfis e permissões</h2><p className="muted">Perfis suportados: ADMIN, MANAGER, AGENT e VIEWER. A gestão de usuários depende da configuração de autenticação do ambiente.</p></section>}
    {active === 'Sistema' && <section className="panel setting-card"><span className="eyebrow">STATUS INTERNO</span><h2>Ambiente</h2><p className="muted">Modo atual: {d?.testMode ? 'TEST_MODE' : 'produção'} · Provider: Meta WhatsApp Cloud API · Endpoint de webhook: /webhooks/whatsapp.</p></section>}
    {confirmPause && <Modal title="Pausar todos os envios" onClose={() => setConfirmPause(false)}><p className="hint">Novos envios serão bloqueados até a reativação administrativa.</p><div className="modal-actions"><button className="ghost" onClick={() => setConfirmPause(false)}>Cancelar</button><button className="danger" onClick={() => { setConfirmPause(false); change(true); }}>Confirmar pausa</button></div></Modal>}</>;
}
