import React, { useEffect, useMemo, useState } from 'react';
import { get, patch, post } from '../services/api';
import { Lead, Task } from '../types';
import { Modal, ToastState } from '../components/Toast';

export function Tasks({ leads, notify }: { leads: Lead[]; notify: (toast: ToastState) => void }) {
  const [data, setData] = useState<Task[]>([]); const [filter, setFilter] = useState('all'); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Task>(); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); return get<{ data: Task[] }>('/api/tasks').then((result) => setData(result.data)).catch((error: Error) => notify({ kind: 'error', title: 'Falha ao carregar tarefas', description: error.message })).finally(() => setLoading(false)); };
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => { const now = new Date(); const end = new Date(now); end.setHours(23, 59, 59, 999); return data.filter((task) => { const due = task.dueDate ? new Date(task.dueDate) : undefined; if (filter === 'completed') return task.completed; if (filter === 'today') return !task.completed && !!due && due.toDateString() === now.toDateString(); if (filter === 'overdue') return !task.completed && !!due && due < now; if (filter === 'upcoming') return !task.completed && (!due || due >= end); return filter === 'all'; }); }, [data, filter]);
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const body = { title: String(values.title), description: String(values.description || ''), assignedTo: String(values.assignedTo || '') || undefined, leadId: String(values.leadId), dueDate: values.dueDate ? new Date(String(values.dueDate)).toISOString() : undefined }; if (editing) { await patch(`/api/tasks/${editing.id}`, body); notify({ kind: 'success', title: 'Tarefa atualizada', description: 'Alterações confirmadas pelo backend.' }); } else { await post('/api/tasks', body); notify({ kind: 'success', title: 'Tarefa criada', description: 'Follow-up salvo no backend.' }); } setModal(false); setEditing(undefined); void load(); } catch (error) { notify({ kind: 'error', title: 'Falha ao salvar tarefa', description: (error as Error).message }); } };
  const toggle = async (task: Task) => { try { await patch(`/api/tasks/${task.id}`, { completed: !task.completed }); notify({ kind: 'success', title: task.completed ? 'Tarefa reaberta' : 'Tarefa concluída' }); void load(); } catch (error) { notify({ kind: 'error', title: 'Falha ao atualizar tarefa', description: (error as Error).message }); } };
  const close = () => { setModal(false); setEditing(undefined); };
  return <><section className="hero-row"><p className="muted">Follow-ups persistentes para a operação comercial.</p><button className="primary" onClick={() => setModal(true)}>＋ Criar tarefa</button></section><div className="filter-tabs">{[['all', 'Todas'], ['today', 'Hoje'], ['overdue', 'Atrasadas'], ['upcoming', 'Próximas'], ['completed', 'Concluídas']].map(([value, label]) => <button className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div><section className="panel task-list">{loading ? <div className="loading-inline">Carregando tarefas…</div> : shown.map((task) => <div className={`task-row ${task.completed ? 'done' : ''}`} key={task.id}><button className="check" onClick={() => void toggle(task)} aria-label={task.completed ? 'Reabrir tarefa' : 'Concluir tarefa'}>{task.completed ? '✓' : ''}</button><div><b>{task.title}</b><small>{task.description || 'Sem descrição'}</small><small>{leads.find((lead) => lead.id === task.leadId)?.name || 'Lead'} · {task.dueDate ? new Date(task.dueDate).toLocaleString('pt-BR') : 'Sem prazo'}</small></div><button className="table-action" onClick={() => { setEditing(task); setModal(true); }}>Editar</button><button className="table-action" onClick={() => void toggle(task)}>{task.completed ? 'Reabrir' : 'Concluir'}</button></div>)}{!loading && !shown.length && <div className="empty"><div className="empty-mark">◇</div><h2>Nenhuma tarefa nesta visão</h2><p>Crie um follow-up para manter a operação em movimento.</p><button className="ghost" onClick={() => setModal(true)}>Criar tarefa</button></div>}</section>{modal && <Modal title={editing ? 'Editar tarefa' : 'Criar tarefa'} onClose={close}><form onSubmit={save}><label>Título<input name="title" defaultValue={editing?.title} required autoFocus /></label><label>Descrição<textarea name="description" defaultValue={editing?.description} /></label><label>Responsável<input name="assignedTo" defaultValue={editing?.assignedTo} placeholder="Responsável" /></label><label>Lead<select name="leadId" defaultValue={editing?.leadId} required>{leads.map((lead) => <option value={lead.id} key={lead.id}>{lead.name}</option>)}</select></label><label>Prazo<input name="dueDate" type="datetime-local" defaultValue={editing?.dueDate?.slice(0, 16)} /></label><div className="modal-actions"><button type="button" className="ghost" onClick={close}>Cancelar</button><button className="primary">{editing ? 'Salvar alterações' : 'Salvar tarefa'}</button></div></form></Modal>}</>;
}
