import Fastify, { FastifyRequest } from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import formbody from '@fastify/formbody';
import cookie from '@fastify/cookie';
import rateLimit from '@fastify/rate-limit';
import fastifyStatic from '@fastify/static';
import path from 'node:path';
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { env } from './config.js';
import { can, normalizePhone, STATUSES } from './domain.js';
import { MemoryStore } from './store.js';
import { createProvider, WhatsAppProvider } from './providers/whatsapp/index.js';
import { SendQueue } from './queue.js';
import { registerOperationalRoutes } from './operationalRoutes.js';
import { PrismaPersistence } from './persistence.js';
import { registerProspectingRoutes } from './prospectingRoutes.js';
import { ProspectingQueue } from './prospectingQueue.js';
import { GeoapifyProvider } from './providers/discovery/GeoapifyProvider.js';

const leadSchema = z.object({
  name: z.string().min(1), company: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional().or(z.literal('')),
  instagram: z.string().optional(), googleMaps: z.string().optional(), site: z.string().optional(), city: z.string().optional(), state: z.string().optional(), niche: z.string().optional(), source: z.string().optional(), observations: z.string().optional(), nextFollowUpAt: z.string().datetime().optional(), lastContactAt: z.string().datetime().optional(), siteModelSent: z.string().optional(), proposedValue: z.coerce.number().nonnegative().optional(), proposalDate: z.string().datetime().optional(),
  status: z.enum(STATUSES).optional(), consentStatus: z.enum(['UNKNOWN', 'OPTED_IN', 'OPTED_OUT']).optional(), consentSource: z.string().optional()
});
const webhookSchema = z.object({
  entry: z.array(z.object({
    changes: z.array(z.object({
      value: z.object({
        messages: z.array(z.object({ id: z.string(), from: z.string(), text: z.object({ body: z.string() }).optional() })).optional(),
        statuses: z.array(z.object({ id: z.string(), status: z.string() })).optional()
      }).passthrough()
    }).passthrough())
  }).passthrough()).default([])
}).passthrough();
type AppRole = 'ADMIN' | 'MANAGER' | 'AGENT' | 'VIEWER';
function roleFor(request: FastifyRequest): AppRole | null {
  if (env.NODE_ENV !== 'production') {
    const header = request.headers['x-user-role'];
    if (typeof header === 'string' && ['ADMIN', 'MANAGER', 'AGENT', 'VIEWER'].includes(header)) return header as AppRole;
  }
  const token = request.cookies?.session || request.headers.authorization?.replace('Bearer ', '');
  if (token) try { return (jwt.verify(token, env.JWT_SECRET) as { role: AppRole }).role; } catch { return null; }
  return env.NODE_ENV === 'production' ? null : 'ADMIN';
}
function protect(request: FastifyRequest, action: 'read' | 'write' | 'campaign' | 'send' | 'admin') { const role = roleFor(request); if (!role) throw Object.assign(new Error('Autenticação obrigatória.'), { statusCode: 401 }); if (!can(role, action)) throw Object.assign(new Error('Permissão insuficiente.'), { statusCode: 403 }); }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : 'Erro inesperado.'; }

export function buildApp(opts: { store?: MemoryStore; provider?: WhatsAppProvider; persistence?: PrismaPersistence } = {}) {
  const store = opts.store || new MemoryStore(env.TEST_MODE, opts.persistence); const provider = opts.provider || createProvider(); const queue = new SendQueue(store, provider); const prospectingQueue = new ProspectingQueue(store);
  const app = Fastify({ logger: { redact: ['req.headers.authorization', '*.token', '*.password'] } });
  app.addHook('onClose', async () => { await queue.close(); await prospectingQueue.close(); });
  app.removeContentTypeParser('application/json');
  app.addContentTypeParser('application/json', { parseAs: 'string' }, (request, body, done) => { try { (request as FastifyRequest & { rawBody?: Buffer }).rawBody = Buffer.from(String(body)); done(null, JSON.parse(String(body))); } catch (error) { done(error as Error, undefined); } });
  app.register(helmet); app.register(formbody); app.register(cookie); app.register(rateLimit, { max: 120, timeWindow: '1 minute' }); app.register(cors, { origin: env.ALLOWED_ORIGINS.split(',').map((item) => item.trim()), credentials: true });
  app.addHook('onRequest', (request, reply, done) => { const exempt = request.url === '/api/auth/login' || request.url.startsWith('/api/public/') || request.url.startsWith('/webhooks/'); if (env.NODE_ENV === 'production' && !exempt && ['POST', 'PATCH', 'DELETE', 'PUT'].includes(request.method)) { const csrfCookie = request.cookies?.csrf; const csrfHeader = request.headers['x-csrf-token']; if (!csrfCookie || typeof csrfHeader !== 'string' || csrfCookie !== csrfHeader) return done(Object.assign(new Error('CSRF token inválido.'), { statusCode: 403 })); } done(); });
  app.addHook('preValidation', (request, reply, done) => { if (request.method === 'POST' && request.url === '/webhooks/whatsapp') { const parsed = webhookSchema.safeParse(request.body); if (!parsed.success) return done(Object.assign(new Error('Payload de webhook inválido.'), { statusCode: 400 })); request.body = parsed.data; } done(); });
  app.setErrorHandler((error, request, reply) => { request.log.error({ err: error, message: errorMessage(error) }, 'request failed'); reply.status((error as { statusCode?: number }).statusCode || 400).send({ error: 'REQUEST_ERROR', message: errorMessage(error) }); });
  app.get('/health', async () => ({ api: 'ok', database: env.DATABASE_URL ? 'configured' : 'not_configured', redis: env.REDIS_URL ? 'configured' : 'not_configured', worker: 'ok', metaApi: env.TEST_MODE ? 'mock-test-mode' : 'configured' }));
  app.get('/api/integrations', async () => { const geoapifyStatus = !env.GEOAPIFY_API_KEY ? 'Não configurado' : await new GeoapifyProvider().checkConnection() ? 'Ativo' : 'Erro'; return { data: [
    { name: 'Geoapify', status: geoapifyStatus, detail: 'Places API e Geocoding API no backend.', requirement: 'Requer GEOAPIFY_API_KEY no servidor.' },
    { name: 'OpenStreetMap', status: 'Disponível', detail: 'Dados públicos auxiliares e tiles.', requirement: 'Limites de uso públicos.' },
    { name: 'Busca Web', status: env.SEARCH_PROVIDER_API_KEY ? 'Ativo' : 'Não configurado', detail: 'Descoberta complementar de presença digital.', requirement: 'Requer SEARCH_PROVIDER_API_KEY.' },
    { name: 'Social Discovery', status: 'Somente público', detail: 'Links públicos de redes sociais.', requirement: 'Não acessa sessões privadas.' },
    { name: 'Map Tiles', status: 'Disponível', detail: 'Mapa MapLibre com coordenadas reais dos resultados.', requirement: 'OpenStreetMap raster tiles.' },
  ], discoveryMode: env.DISCOVERY_MODE, discoveryTestMode: env.DISCOVERY_TEST_MODE }; });
  app.post('/api/auth/login', async (request, reply) => { const body = z.object({ email: z.string().email(), password: z.string() }).parse(request.body); if (body.email !== env.ADMIN_EMAIL || (!env.TEST_MODE && body.password !== env.ADMIN_PASSWORD)) return reply.status(401).send({ error: 'INVALID_CREDENTIALS', message: 'Credenciais inválidas.' }); const token = jwt.sign({ sub: 'demo-admin', role: 'ADMIN', email: body.email }, env.JWT_SECRET, { expiresIn: '8h' }); const csrf = crypto.randomBytes(24).toString('hex'); reply.setCookie('session', token, { httpOnly: true, secure: env.NODE_ENV === 'production', sameSite: 'lax', path: '/', maxAge: 8 * 60 * 60 }); reply.setCookie('csrf', csrf, { httpOnly: false, secure: env.NODE_ENV === 'production', sameSite: 'lax', path: '/', maxAge: 8 * 60 * 60 }); return { user: { id: 'demo-admin', email: body.email, name: 'Admin Impulse', role: 'ADMIN' } }; });
  app.get('/api/dashboard', async (request) => { protect(request, 'read'); return store.dashboard(); });
  app.get('/api/leads', async (request) => { protect(request, 'read'); const q = request.query as Record<string, string | undefined>; const search = (q.search || '').toLowerCase(); let leads = [...store.leads.values()].filter((lead) => !search || [lead.name, lead.company, lead.normalizedPhone, lead.city, lead.instagram, lead.niche].some((value) => value?.toLowerCase().includes(search))).filter((lead) => !q.status || lead.status === q.status).filter((lead) => !q.city || lead.city === q.city).filter((lead) => !q.niche || lead.niche === q.niche).filter((lead) => !q.consentStatus || lead.consentStatus === q.consentStatus); const page = Math.max(1, Number(q.page) || 1); const limit = Math.min(100, Math.max(1, Number(q.limit) || 25)); return { data: leads.slice((page - 1) * limit, page * limit), total: leads.length, page, limit }; });
  app.post('/api/leads', async (request) => { protect(request, 'write'); const body = leadSchema.parse(request.body); if (body.consentStatus === 'OPTED_OUT') body.status = 'NAO_CONTATAR'; const result = store.createLead(body); if (result.duplicate) return { duplicate: { id: result.duplicate.id, name: result.duplicate.name, company: result.duplicate.company, message: `Este telefone já pertence ao lead ${result.duplicate.company || result.duplicate.name}.` } }; return { data: result.lead }; });
  app.patch('/api/leads/:id', async (request) => { protect(request, 'write'); const body = leadSchema.partial().parse(request.body); const id = (request.params as { id: string }).id; if (body.consentStatus === 'OPTED_OUT') Object.assign(body, { status: 'NAO_CONTATAR' }); const lead = store.updateLead(id, body); if (!lead) throw Object.assign(new Error('Lead não encontrado.'), { statusCode: 404 }); if (body.consentStatus === 'OPTED_OUT') store.addHistory(id, 'OPT_OUT_REGISTERED'); if (body.consentStatus === 'OPTED_IN') store.addHistory(id, 'OPT_IN_REGISTERED'); return { data: lead }; });
  app.delete('/api/leads/:id', async (request) => { protect(request, 'admin'); const id = (request.params as { id: string }).id; if (!store.deleteLead(id)) throw Object.assign(new Error('Lead não encontrado.'), { statusCode: 404 }); return { ok: true }; });
  app.get('/api/leads/:id/timeline', async (request) => { protect(request, 'read'); const id = (request.params as { id: string }).id; return { lead: store.leads.get(id), history: store.histories.filter((item) => item.leadId === id), messages: store.messages.filter((item) => item.conversationId === id) }; });
  app.post('/api/leads/:id/notes', async (request) => { protect(request, 'write'); const id = (request.params as { id: string }).id; const body = z.object({ body: z.string().min(1) }).parse(request.body); store.addHistory(id, 'NOTE_CREATED', body.body); return { ok: true }; });
  app.post('/api/leads/import', async (request) => { protect(request, 'write'); const body = z.object({ rows: z.array(leadSchema) }).parse(request.body); const results = body.rows.map((row) => store.createLead(row)); return { imported: results.filter((item) => item.lead).length, duplicates: results.filter((item) => item.duplicate).length, invalid: 0 }; });
  app.get('/api/leads/export', async (request, reply) => { protect(request, 'read'); const format = (request.query as { format?: string }).format; const leads = [...store.leads.values()]; store.addHistory('system', 'EXPORT_PERFORMED', format || 'json'); if (format === 'csv') { reply.type('text/csv'); return ['nome,empresa,telefone,cidade,status,consentimento', ...leads.map((lead) => [lead.name, lead.company || '', lead.phone || '', lead.city || '', lead.status, lead.consentStatus].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); } return leads; });
  app.get('/api/templates', async (request) => { protect(request, 'read'); return { data: store.templates }; }); app.post('/api/templates/sync', async (request) => { protect(request, 'campaign'); return { data: await provider.getTemplates() }; });
  app.get('/api/settings/whatsapp', async (request) => { protect(request, 'read'); return { ...store.settings, officialApiGuard: true, lastEvent: store.settings.lastWebhook }; });
  app.post('/api/settings/whatsapp/test', async (request) => { protect(request, 'admin'); try { return { ok: true, provider: 'META WHATSAPP CLOUD API', testMode: env.TEST_MODE, phone: await provider.getPhoneInfo(), diagnostics: ['Credenciais verificadas', 'Número consultado', 'WABA validável', 'Permissões dependem do token', 'Webhook configurado em /webhooks/whatsapp'] }; } catch (error) { return { ok: false, error: errorMessage(error) }; } });
  app.post('/api/settings/pause', async (request) => { protect(request, 'admin'); await queue.pause(); return { paused: true, message: 'Envios pausados preventivamente.' }; }); app.post('/api/settings/resume', async (request) => { protect(request, 'admin'); z.object({ confirm: z.literal(true) }).parse(request.body); await queue.resume(); return { paused: false }; });
  app.get('/api/conversations', async (request) => { protect(request, 'read'); const leads = [...store.leads.values()]; return { data: leads.filter((lead) => lead.phone).map((lead) => ({ id: lead.id, lead, lastMessage: store.messages.filter((message) => message.conversationId === lead.id).at(-1) })) }; }); app.get('/api/conversations/:id/messages', async (request) => { protect(request, 'read'); const id = (request.params as { id: string }).id; return { data: store.messages.filter((message) => message.conversationId === id) }; });
  app.post('/api/conversations/:id/simulate-inbound', async (request) => { protect(request, 'write'); if (!env.TEST_MODE) throw Object.assign(new Error('Simulação disponível somente em TEST_MODE.'), { statusCode: 409 }); const id = (request.params as { id: string }).id; const lead = store.leads.get(id); if (!lead) throw Object.assign(new Error('Lead não encontrado.'), { statusCode: 404 }); const body = z.object({ text: z.string().min(1) }).parse(request.body); const message = store.addMessage({ conversationId: id, direction: 'INBOUND', type: 'TEXT', content: body.text, status: 'DELIVERED', providerMessageId: `mock-in-${crypto.randomUUID()}`, idempotencyKey: `mock-in:${crypto.randomUUID()}` }); store.updateLead(id, { status: 'RESPONDEU' }); return { data: message, simulation: true }; });
  app.post('/api/conversations/:id/messages', async (request) => { protect(request, 'send'); const id = (request.params as { id: string }).id; const lead = store.leads.get(id); if (!lead) throw Object.assign(new Error('Lead não encontrado.'), { statusCode: 404 }); if (!lead.normalizedPhone) throw new Error('Lead sem telefone normalizado.'); if (lead.consentStatus !== 'OPTED_IN' || lead.status === 'NAO_CONTATAR') throw new Error(lead.consentStatus === 'OPTED_OUT' ? 'Este contato solicitou que não sejam enviadas novas mensagens.' : 'Consentimento OPTED_IN é obrigatório antes do envio.'); const body = z.object({ text: z.string().optional(), templateName: z.string().optional(), idempotencyKey: z.string().default(crypto.randomUUID()) }).refine((value) => value.text || value.templateName, { message: 'Texto ou template é obrigatório.' }).parse(request.body); if (body.templateName && !store.templates.some((template) => template.name === body.templateName && template.status === 'APPROVED')) throw new Error('Template não aprovado ou indisponível.'); const lastInbound = store.messages.filter((message) => message.conversationId === id && message.direction === 'INBOUND').at(-1); if (!body.templateName && (!lastInbound || Date.now() - Date.parse(lastInbound.createdAt) > 86400000)) throw new Error('Necessário utilizar template aprovado.'); const message = store.addMessage({ conversationId: id, direction: 'OUTBOUND', type: body.templateName ? 'TEMPLATE' : 'TEXT', content: body.text || '', templateName: body.templateName, status: 'QUEUED', idempotencyKey: body.idempotencyKey }); queue.enqueue(message); return { data: message }; });
  app.post('/api/public/leads', async (request) => { const body = z.object({ name: z.string().min(1), company: z.string().optional(), phone: z.string().min(8), message: z.string().optional(), consent: z.literal(true), formVersion: z.string().optional(), captchaToken: z.string().optional() }).parse(request.body); if (env.PUBLIC_LEAD_CAPTCHA_SECRET && body.captchaToken !== env.PUBLIC_LEAD_CAPTCHA_SECRET) throw Object.assign(new Error('Captcha inválido.'), { statusCode: 400 }); const result = store.createLead({ name: body.name, company: body.company, phone: body.phone, observations: body.message, source: 'SITE', consentStatus: 'OPTED_IN', consentSource: 'SITE', consentDate: new Date().toISOString() }); if (result.duplicate) return { accepted: false, duplicate: true }; return { accepted: true, id: result.lead?.id }; });
  app.get('/webhooks/whatsapp', async (request, reply) => { const query = request.query as Record<string, string | undefined>; if (query['hub.mode'] === 'subscribe' && query['hub.verify_token'] === env.META_WEBHOOK_VERIFY_TOKEN) return reply.type('text/plain').send(query['hub.challenge']); return reply.status(403).send('Forbidden'); });
  app.post('/webhooks/whatsapp', async (request, reply) => { const raw = (request as FastifyRequest & { rawBody?: Buffer }).rawBody || (Buffer.isBuffer(request.body) ? request.body : Buffer.from(JSON.stringify(request.body))); const signature = typeof request.headers['x-hub-signature-256'] === 'string' ? request.headers['x-hub-signature-256'] : undefined; if (!env.TEST_MODE && !provider.validateWebhookSignature(raw, signature)) return reply.status(401).send({ error: 'INVALID_SIGNATURE' }); const payload = request.body as { entry?: Array<{ changes?: Array<{ value?: { messages?: Array<{ id: string; from: string; text?: { body: string } }>; statuses?: Array<{ id: string; status: string; errors?: Array<{ code: string; title?: string }> }> } }> }> }; const ids = (payload.entry || []).flatMap((entry) => (entry.changes || []).flatMap((change) => [...(change.value?.messages || []).map((item) => `message:${item.id}`), ...(change.value?.statuses || []).map((item) => `status:${item.id}:${item.status}`)])); const eventId = ids.length ? ids.sort().join('|') : crypto.createHash('sha256').update(raw).digest('hex'); if (store.histories.some((item) => item.details === `WEBHOOK:${eventId}`)) return { ok: true, idempotent: true }; store.addHistory('system', 'WEBHOOK_RECEIVED', `WEBHOOK:${eventId}`); store.settings.lastWebhook = new Date().toISOString(); for (const entry of payload.entry || []) for (const change of entry.changes || []) { for (const incoming of change.value?.messages || []) { const lead = [...store.leads.values()].find((item) => item.normalizedPhone === normalizePhone(incoming.from)); if (lead) { store.updateLead(lead.id, { status: 'RESPONDEU' }); store.addMessage({ conversationId: lead.id, direction: 'INBOUND', type: 'TEXT', content: incoming.text?.body || '[mensagem]', status: 'DELIVERED', providerMessageId: incoming.id, idempotencyKey: `in:${incoming.id}` }); } } for (const status of change.value?.statuses || []) { const message = store.messages.find((item) => item.providerMessageId === status.id); if (message) message.status = status.status.toUpperCase() as typeof message.status; } } return { ok: true }; });
  app.register(fastifyStatic, { root: path.join(process.cwd(), 'dist/web'), prefix: '/' }); app.setNotFoundHandler((request, reply) => { if (request.method === 'GET' && !request.url.startsWith('/api/') && !request.url.startsWith('/webhooks/')) return reply.sendFile('index.html'); return reply.status(404).send({ error: 'NOT_FOUND' }); });
  registerOperationalRoutes(app, store, queue);
  registerProspectingRoutes(app, store, prospectingQueue);
  return app;
}
