import { FastifyInstance, FastifyRequest } from 'fastify';
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import { env } from './config.js';
import { z } from 'zod';
import { MemoryStore } from './store.js';
import { SendQueue } from './queue.js';

function assertCanOperate(request: FastifyRequest) {
  const headerRole = env.NODE_ENV !== 'production' ? request.headers['x-user-role'] : undefined;
  let role = typeof headerRole === 'string' ? headerRole : undefined;
  const token = request.cookies?.session || request.headers.authorization?.replace('Bearer ', '');
  if (env.NODE_ENV === 'production') {
    if (!token) throw Object.assign(new Error('Autenticação obrigatória.'), { statusCode: 401 });
    try { role = (jwt.verify(token, env.JWT_SECRET) as { role: string }).role; } catch { throw Object.assign(new Error('Sessão inválida.'), { statusCode: 401 }); }
  }
  if (role === 'VIEWER') throw Object.assign(new Error('Permissão insuficiente.'), { statusCode: 403 });
}

export function registerOperationalRoutes(app: FastifyInstance, store: MemoryStore, queue: SendQueue) {
  const campaignSchema = z.object({ name: z.string().min(1), templateName: z.string().min(1), segment: z.record(z.string(), z.string()).default({}), scheduledAt: z.string().datetime().optional() });
  app.get('/api/campaigns', async (request) => { assertCanOperate(request); const data = store.campaigns.map((campaign) => { const messages = campaign.recipientIds.map((leadId) => store.messages.filter((message) => message.conversationId === leadId && message.idempotencyKey.startsWith(`campaign:${campaign.id}:`)).at(-1)).filter(Boolean); return { ...campaign, sent: messages.filter((message) => ['SENT', 'DELIVERED', 'READ'].includes(message!.status)).length, delivered: messages.filter((message) => ['DELIVERED', 'READ'].includes(message!.status)).length, failed: messages.filter((message) => message!.status === 'FAILED').length }; }); return { data }; });
  app.post('/api/campaigns', async (request) => { assertCanOperate(request); const body = campaignSchema.parse(request.body); const segment = body.segment; const recipients = [...store.leads.values()].filter((lead) => lead.consentStatus === 'OPTED_IN' && lead.status !== 'NAO_CONTATAR' && (!segment.city || lead.city === segment.city) && (!segment.state || lead.state === segment.state) && (!segment.niche || lead.niche === segment.niche) && (!segment.status || lead.status === segment.status)).map((lead) => lead.id); const campaign = { id: crypto.randomUUID(), name: body.name, templateName: body.templateName, segment, status: 'DRAFT', createdAt: new Date().toISOString(), scheduledAt: body.scheduledAt, createdBy: 'demo-admin', recipientIds: recipients }; store.campaigns.push(campaign); store.persistCampaign(campaign); store.addHistory('system', 'CAMPAIGN_CREATED', `${campaign.id}:${recipients.length} elegíveis`); return { data: campaign, estimate: { eligible: recipients.length, blockedWithoutOptIn: [...store.leads.values()].filter((lead) => lead.consentStatus !== 'OPTED_IN').length } }; });
  app.post('/api/campaigns/:id/approve', async (request) => { assertCanOperate(request); const body = z.object({ confirm: z.literal(true) }).parse(request.body); void body; const id = (request.params as { id: string }).id; const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw Object.assign(new Error('Campanha não encontrada.'), { statusCode: 404 }); campaign.status = 'SCHEDULED'; store.persistCampaign(campaign); store.addHistory('system', 'CAMPAIGN_APPROVED', id); return { data: campaign }; });
  app.post('/api/campaigns/:id/start', async (request) => { assertCanOperate(request); z.object({ confirm: z.literal(true) }).parse(request.body); const id = (request.params as { id: string }).id; const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw Object.assign(new Error('Campanha não encontrada.'), { statusCode: 404 }); if (campaign.status !== 'SCHEDULED') throw new Error('Campanha precisa de aprovação manual antes de iniciar.'); if (store.settings.queuePaused) throw new Error('Envios pausados preventivamente. Reative a fila antes de iniciar a campanha.'); const eligible = campaign.recipientIds.filter((leadId) => { const lead = store.leads.get(leadId); return Boolean(lead?.normalizedPhone && lead.consentStatus === 'OPTED_IN' && lead.status !== 'NAO_CONTATAR'); }); const previousRecipients = campaign.recipientIds; campaign.recipientIds = eligible; campaign.status = 'RUNNING'; store.persistCampaign(campaign); try { for (const leadId of eligible) { if (store.settings.queuePaused) throw new Error('Envios pausados durante a campanha.'); const lead = store.leads.get(leadId); if (!lead?.normalizedPhone || lead.consentStatus !== 'OPTED_IN' || lead.status === 'NAO_CONTATAR') continue; const message = store.addMessage({ conversationId: leadId, direction: 'OUTBOUND', type: 'TEMPLATE', content: '', templateName: campaign.templateName, status: 'QUEUED', idempotencyKey: `campaign:${id}:${leadId}` }); queue.enqueue(message); } } catch (error) { campaign.status = 'PAUSED'; campaign.recipientIds = previousRecipients; store.persistCampaign(campaign); throw error; } return { data: campaign, enqueued: eligible.length }; });
  app.post('/api/campaigns/:id/pause', async (request) => { assertCanOperate(request); const id = (request.params as { id: string }).id; const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw Object.assign(new Error('Campanha não encontrada.'), { statusCode: 404 }); campaign.status = 'PAUSED'; store.persistCampaign(campaign); return { data: campaign }; });
  app.get('/api/tasks', async (request) => { assertCanOperate(request); return { data: store.tasks }; });
  app.post('/api/tasks', async (request) => { assertCanOperate(request); const body = z.object({ leadId: z.string(), title: z.string().min(1), description: z.string().optional(), dueDate: z.string().datetime().optional(), assignedTo: z.string().optional() }).parse(request.body); const task = { id: crypto.randomUUID(), ...body, completed: false, createdAt: new Date().toISOString() }; store.tasks.push(task); store.persistTask(task); store.addHistory(body.leadId, 'TASK_CREATED', body.title); return { data: task }; });
  app.patch('/api/tasks/:id', async (request) => { assertCanOperate(request); const task = store.tasks.find((item) => item.id === (request.params as { id: string }).id); if (!task) throw Object.assign(new Error('Tarefa não encontrada.'), { statusCode: 404 }); const before = task.completed; Object.assign(task, z.object({ title: z.string().min(1).optional(), description: z.string().optional(), dueDate: z.string().datetime().optional(), assignedTo: z.string().optional(), completed: z.boolean().optional() }).parse(request.body)); store.persistTask(task); if (typeof task.completed === 'boolean' && task.completed !== before) store.addHistory(task.leadId, task.completed ? 'TASK_COMPLETED' : 'TASK_REOPENED', task.title); return { data: task }; });
  app.get('/api/quality', async (request) => { assertCanOperate(request); const messages = store.messages; const count = (status: string) => messages.filter((message) => message.status === status).length; const sent = count('SENT') + count('DELIVERED') + count('READ'); return { sent, delivered: count('DELIVERED') + count('READ'), read: count('READ'), failed: count('FAILED'), deliveryRate: sent ? (count('DELIVERED') + count('READ')) / sent : 0, failureRate: messages.length ? count('FAILED') / messages.length : 0, optOuts: [...store.leads.values()].filter((lead) => lead.consentStatus === 'OPTED_OUT').length, recentErrors: messages.filter((message) => message.status === 'FAILED').slice(-10), deadLetters: store.settings.deadLetters.slice(-20), integration: store.settings, lastWebhook: store.settings.lastWebhook }; });
  app.get('/api/reports', async (request) => { assertCanOperate(request); const data = store.histories.reduce<Record<string, number>>((result, item) => { const day = item.createdAt.slice(0, 10); result[day] = (result[day] || 0) + 1; return result; }, {}); return { activityByDay: data, leadsByCity: store.dashboard().byCity, leadsByNiche: store.dashboard().byNiche, conversions: store.dashboard().pipeline }; });
}
