import { PrismaClient } from '@prisma/client';
import crypto from 'node:crypto';
import { MemoryStore } from './store.js';
import { Lead, History, Message } from './domain.js';

export class PrismaPersistence {
  readonly prisma = new PrismaClient();
  async load(store: MemoryStore) {
    const leads = await this.prisma.lead.findMany({ include: { consent: true, optOut: true } });
    for (const item of leads) store.leads.set(item.id, { id: item.id, name: item.name, company: item.company || undefined, phone: item.phone || undefined, normalizedPhone: item.normalizedPhone || undefined, email: item.email || undefined, instagram: item.instagram || undefined, googleMaps: item.googleMaps || undefined, site: item.site || undefined, city: item.city || undefined, state: item.state || undefined, niche: item.niche || undefined, source: item.source || undefined, observations: item.observations || undefined, nextFollowUpAt: item.nextFollowUpAt?.toISOString(), lastContactAt: item.lastContactAt?.toISOString(), siteModelSent: item.siteModelSent || undefined, proposedValue: item.proposedValue ? Number(item.proposedValue) : undefined, proposalDate: item.proposalDate?.toISOString(), status: item.status, assignedUserId: item.assignedUserId || undefined, consentStatus: item.consent?.status || 'UNKNOWN', consentSource: item.consent?.source || undefined, consentDate: item.consent?.date?.toISOString(), createdAt: item.createdAt.toISOString(), updatedAt: item.updatedAt.toISOString() });
    const history = await this.prisma.leadHistory.findMany(); store.histories.push(...history.map((item) => ({ id: item.id, leadId: item.leadId, type: item.type, details: typeof item.details === 'string' ? item.details : undefined, userId: item.userId || undefined, createdAt: item.createdAt.toISOString() })));
    const templates = await this.prisma.template.findMany(); if (templates.length) store.templates = templates.map((item) => ({ id: item.id, name: item.name, language: item.language, category: item.category, status: item.status, updatedAt: item.updatedAt.toISOString() }));
    const messages = await this.prisma.message.findMany(); store.messages.push(...messages.map((item) => ({ id: item.id, conversationId: item.conversationId, providerMessageId: item.providerMessageId || undefined, direction: item.direction, type: item.type, content: item.content, templateName: item.templateName || undefined, status: item.status, idempotencyKey: item.idempotencyKey, createdAt: item.createdAt.toISOString(), errorMessage: item.errorMessage || undefined })));
    const campaigns = await this.prisma.campaign.findMany({ include: { recipients: true } }); store.campaigns.push(...campaigns.map((item) => ({ id: item.id, name: item.name, templateName: item.templateName, segment: item.segment as Record<string, string>, status: item.status, createdAt: item.createdAt.toISOString(), scheduledAt: item.scheduledAt?.toISOString(), createdBy: item.createdBy, recipientIds: item.recipients.map((recipient) => recipient.leadId) })));
    const tasks = await this.prisma.task.findMany(); store.tasks.push(...tasks.map((item) => ({ id: item.id, leadId: item.leadId, title: item.title, description: item.description || undefined, dueDate: item.dueDate?.toISOString(), assignedTo: item.assignedTo || undefined, completed: item.completed, createdAt: item.createdAt.toISOString() })));
  }
  async saveLead(lead: Lead) { await this.prisma.lead.upsert({ where: { id: lead.id }, update: { name: lead.name, company: lead.company, phone: lead.phone, normalizedPhone: lead.normalizedPhone, email: lead.email, instagram: lead.instagram, googleMaps: lead.googleMaps, site: lead.site, city: lead.city, state: lead.state, niche: lead.niche, source: lead.source, observations: lead.observations, nextFollowUpAt: lead.nextFollowUpAt ? new Date(lead.nextFollowUpAt) : undefined, lastContactAt: lead.lastContactAt ? new Date(lead.lastContactAt) : undefined, siteModelSent: lead.siteModelSent, proposedValue: lead.proposedValue, proposalDate: lead.proposalDate ? new Date(lead.proposalDate) : undefined, status: lead.status as never, assignedUserId: lead.assignedUserId }, create: { id: lead.id, name: lead.name, company: lead.company, phone: lead.phone, normalizedPhone: lead.normalizedPhone, email: lead.email, instagram: lead.instagram, googleMaps: lead.googleMaps, site: lead.site, city: lead.city, state: lead.state, niche: lead.niche, source: lead.source, observations: lead.observations, nextFollowUpAt: lead.nextFollowUpAt ? new Date(lead.nextFollowUpAt) : undefined, lastContactAt: lead.lastContactAt ? new Date(lead.lastContactAt) : undefined, siteModelSent: lead.siteModelSent, proposedValue: lead.proposedValue, proposalDate: lead.proposalDate ? new Date(lead.proposalDate) : undefined, status: lead.status as never, assignedUserId: lead.assignedUserId } }); await this.prisma.consent.upsert({ where: { leadId: lead.id }, update: { status: lead.consentStatus as never, source: lead.consentSource, date: lead.consentDate ? new Date(lead.consentDate) : undefined }, create: { leadId: lead.id, status: lead.consentStatus as never, source: lead.consentSource, date: lead.consentDate ? new Date(lead.consentDate) : undefined } }); if (lead.consentStatus === 'OPTED_OUT') await this.prisma.optOut.upsert({ where: { leadId: lead.id }, update: { reason: 'Solicitação registrada' }, create: { leadId: lead.id, reason: 'Solicitação registrada' } }); else await this.prisma.optOut.deleteMany({ where: { leadId: lead.id } }); }
  async saveHistory(item: History) { await this.prisma.leadHistory.create({ data: { id: item.id, leadId: item.leadId, type: item.type, details: item.details, userId: item.userId } as never }); }
  async saveMessage(item: Message) { await this.prisma.conversation.upsert({ where: { id: item.conversationId }, update: { lastMessageAt: new Date(item.createdAt) }, create: { id: item.conversationId, leadId: item.conversationId, lastMessageAt: new Date(item.createdAt) } }); await this.prisma.message.upsert({ where: { id: item.id }, update: { status: item.status as never, providerMessageId: item.providerMessageId, errorMessage: item.errorMessage }, create: { id: item.id, conversationId: item.conversationId, providerMessageId: item.providerMessageId, direction: item.direction as never, type: item.type as never, content: item.content, templateName: item.templateName, status: item.status as never, idempotencyKey: item.idempotencyKey } }); }
  async saveCampaign(item: { id: string; name: string; templateName: string; segment: Record<string, string>; status: string; createdAt: string; scheduledAt?: string; createdBy: string; recipientIds: string[] }) { await this.prisma.campaign.upsert({ where: { id: item.id }, update: { status: item.status as never, scheduledAt: item.scheduledAt ? new Date(item.scheduledAt) : undefined }, create: { id: item.id, name: item.name, templateName: item.templateName, segment: item.segment, status: item.status as never, createdAt: new Date(item.createdAt), scheduledAt: item.scheduledAt ? new Date(item.scheduledAt) : undefined, createdBy: item.createdBy } }); await this.prisma.campaignRecipient.deleteMany({ where: { campaignId: item.id } }); if (item.recipientIds.length) await this.prisma.campaignRecipient.createMany({ data: item.recipientIds.map((leadId) => ({ id: crypto.randomUUID(), campaignId: item.id, leadId })) }); }
  async saveTask(item: { id: string; leadId: string; title: string; description?: string; dueDate?: string; assignedTo?: string; completed: boolean; createdAt: string }) { await this.prisma.task.upsert({ where: { id: item.id }, update: { title: item.title, description: item.description, dueDate: item.dueDate ? new Date(item.dueDate) : undefined, assignedTo: item.assignedTo, completed: item.completed }, create: { id: item.id, leadId: item.leadId, title: item.title, description: item.description, dueDate: item.dueDate ? new Date(item.dueDate) : undefined, assignedTo: item.assignedTo, completed: item.completed, createdAt: new Date(item.createdAt) } }); }
  async deleteLead(id: string) { await this.prisma.lead.delete({ where: { id } }); }
  async close() { await this.prisma.$disconnect(); }
}
