import crypto from 'node:crypto';
import { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { MemoryStore, ProspectBusiness, ProspectSearch } from './store.js';
import { discoveryProviders } from './providers/discovery/index.js';
import { deduplicateBusinesses, normalizeBusiness } from './prospecting.js';
import { ProspectingQueue } from './prospectingQueue.js';

const states = ['Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins'].map((name) => ({ name, uf: name === 'São Paulo' ? 'SP' : name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').slice(0,2).toUpperCase() }));
const cities: Record<string,string[]> = { SP: ['Bauru','Campinas','Guarulhos','Ribeirão Preto','Santos','São José dos Campos','São Paulo','Sorocaba'], RJ: ['Niterói','Nova Friburgo','Petrópolis','Rio de Janeiro','Volta Redonda'], MG: ['Belo Horizonte','Juiz de Fora','Uberlândia'], PR: ['Curitiba','Londrina','Maringá'], BA: ['Feira de Santana','Salvador','Vitória da Conquista'], RS: ['Caxias do Sul','Porto Alegre'], SC: ['Blumenau','Florianópolis','Joinville'] };
const niches = ['Academias','Advocacia','Arquitetura','Barbearias','Buffets','Clínicas de estética','Clínicas odontológicas','Contabilidade','Dentistas','Estética automotiva','Fotografia','Imobiliárias','Lojas de roupas','Psicologia','Restaurantes','Salões de beleza','Veterinárias'];
function assertCan(request: FastifyRequest) { if (request.headers['x-user-role'] === 'VIEWER') throw Object.assign(new Error('Permissão insuficiente.'), { statusCode: 403 }); }
function toBusiness(searchId: string, item: ReturnType<typeof normalizeBusiness>): ProspectBusiness { return { id: crypto.randomUUID(), searchId, externalIds:item.externalIds, name:item.name, normalizedName:item.normalizedName, category:item.category, phone:item.phone, normalizedPhone:item.normalizedPhone, whatsapp:item.whatsapp, email:item.email, instagram:item.instagram, facebook:item.facebook, tiktok:item.tiktok, linkedin:item.linkedin, website:item.website, domain:item.domain, mapsUrl:item.mapsUrl, address:item.address, district:item.district, city:item.city, state:item.state, postalCode:item.postalCode, latitude:item.latitude, longitude:item.longitude, rating:item.rating, reviewsCount:item.reviewsCount, digitalStatus:item.digitalStatus, digitalStatusConfidence:item.confidence, opportunityScore:item.score, scoreBreakdown:item.breakdown, sourceProviders:item.externalIds ? Object.keys(item.externalIds) : [], favorite:false, discarded:false, createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), verifiedAt:new Date().toISOString() }; }
export function registerProspectingRoutes(app: FastifyInstance, store: MemoryStore, prospectingQueue: ProspectingQueue) {
  app.get('/api/prospecting/localities', async (request) => { const uf = (request.query as { state?: string }).state; return { states, cities: uf ? (cities[uf] || []).slice().sort((a,b)=>a.localeCompare(b,'pt-BR')) : [] }; });
  app.get('/api/prospecting/niches', async () => ({ data: niches.slice().sort((a,b)=>a.localeCompare(b,'pt-BR')) }));
  app.get('/api/prospecting/searches', async (request) => { assertCan(request); return { data: store.prospectingSearches.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)) }; });
  app.get('/api/prospecting/searches/:id', async (request) => { assertCan(request); const id=(request.params as {id:string}).id; const search=store.prospectingSearches.find(item=>item.id===id); if(!search) throw Object.assign(new Error('Busca não encontrada.'),{statusCode:404}); return { search, data: store.prospectBusinesses.filter(item=>item.searchId===id && !item.discarded) }; });
  app.post('/api/prospecting/searches', async (request) => {
    assertCan(request); const body=z.object({ state:z.string().min(2), city:z.string().min(2), district:z.string().optional(), niche:z.string().min(2), sourceMode:z.enum(['PRINCIPAL','ALTERNATIVA','AMPLIADA']).default('AMPLIADA'), digitalStatus:z.enum(['UNKNOWN','NO_WEBSITE_FOUND','SOCIAL_ONLY','HAS_WEBSITE']).default('UNKNOWN'), minScore:z.coerce.number().int().min(0).max(100).default(0), quantity:z.coerce.number().int().refine((value)=>[5,10,20,30,50,100,150,200,300,400,500].includes(value),'Quantidade inválida.'), coverageMode:z.enum(['STRICT','INTELLIGENT','BROAD']).default('INTELLIGENT') }).parse(request.body);
    const search:ProspectSearch={id:crypto.randomUUID(),...body,status:'QUEUED',progress:0,providersConsulted:0,uniqueResults:0,noWebsiteCount:0,socialOnlyCount:0,websiteCount:0,createdAt:new Date().toISOString(),resultsCount:0}; store.persistProspectSearch(search); await prospectingQueue.enqueue(search); return { data:search };
  });
  app.post('/api/prospecting/searches/:id/cancel', async (request) => { assertCan(request); const search=store.prospectingSearches.find(item=>item.id===(request.params as {id:string}).id); if(!search) throw Object.assign(new Error('Busca não encontrada.'),{statusCode:404}); if(['COMPLETED','FAILED','CANCELLED'].includes(search.status)) return { data:search }; search.status='CANCELLED'; search.cancelledAt=new Date().toISOString(); store.persistProspectSearch(search); return { data:search }; });
  app.patch('/api/prospecting/businesses/:id', async (request) => { assertCan(request); const item=store.prospectBusinesses.find(value=>value.id===(request.params as {id:string}).id); if(!item) throw Object.assign(new Error('Oportunidade não encontrada.'),{statusCode:404}); const body=z.object({favorite:z.boolean().optional(),discarded:z.boolean().optional(),discardReason:z.string().optional()}).parse(request.body); Object.assign(item,body,{updatedAt:new Date().toISOString()}); store.persistProspectBusiness(item); return { data:item }; });
  app.post('/api/prospecting/businesses/:id/save-lead', async (request) => { assertCan(request); const item=store.prospectBusinesses.find(value=>value.id===(request.params as {id:string}).id); if(!item) throw Object.assign(new Error('Oportunidade não encontrada.'),{statusCode:404}); const result=store.createLead({ name:item.name, company:item.name, phone:item.phone, normalizedPhone:item.normalizedPhone, instagram:item.instagram, site:item.website, googleMaps:item.mapsUrl, city:item.city, state:item.state, niche:item.category, source:`PROSPECTING:${item.searchId}`, observations:`Score de oportunidade: ${item.opportunityScore}. Status digital: ${item.digitalStatus}.` }); if(result.lead) store.addHistory(result.lead.id,'SAVED_AS_LEAD',`PROSPECT_BUSINESS:${item.id}`); return result.duplicate ? { duplicate:result.duplicate } : { data:result.lead }; });
  app.get('/api/prospecting/searches/:id/export', async (request,reply) => { assertCan(request); const id=(request.params as {id:string}).id; const rows=store.prospectBusinesses.filter(item=>item.searchId===id&&!item.discarded); reply.type('text/csv'); return ['Empresa,Telefone,WhatsApp,Instagram,Site,Maps,Cidade,Bairro,Nicho,Score,Status digital',...rows.map(item=>[item.name,item.phone,item.whatsapp,item.instagram,item.website,item.mapsUrl,item.city,item.district,item.category,item.opportunityScore,item.digitalStatus].map(value=>`"${String(value||'').replaceAll('"','""')}"`).join(','))].join('\n'); });
}
export async function runSearch(search: ProspectSearch, store: MemoryStore) {
  try { search.status='RUNNING'; search.startedAt=new Date().toISOString(); store.persistProspectSearch(search); const providers=discoveryProviders(search.sourceMode as 'PRINCIPAL'|'ALTERNATIVA'|'AMPLIADA'); search.providersConsulted=providers.length; const raw=[]; for(const provider of providers){ if(search.status==='CANCELLED')return; raw.push(...await provider.searchBusinesses({state:search.state,city:search.city,district:search.district,niche:search.niche,quantity:search.quantity})); search.progress=Math.min(80,Math.round((raw.length/Math.max(1,search.quantity*providers.length))*80)); store.persistProspectSearch(search); } const normalized=deduplicateBusinesses(raw.map(normalizeBusiness)).filter(item=>item.score>=search.minScore).filter(item=>search.digitalStatus==='UNKNOWN'||item.digitalStatus===search.digitalStatus).slice(0,search.quantity); for(const item of normalized){ if(search.status==='CANCELLED')return; const business=toBusiness(search.id,item); store.persistProspectBusiness(business); } search.progress=100; search.status='COMPLETED'; search.completedAt=new Date().toISOString(); search.resultsCount=normalized.length; search.uniqueResults=normalized.length; search.noWebsiteCount=normalized.filter(item=>item.digitalStatus==='NO_WEBSITE_FOUND').length; search.socialOnlyCount=normalized.filter(item=>item.digitalStatus==='SOCIAL_ONLY').length; search.websiteCount=normalized.filter(item=>item.digitalStatus==='HAS_WEBSITE').length; store.persistProspectSearch(search); } catch(error) { search.status='FAILED'; search.errorMessage=error instanceof Error?error.message:'Falha na busca.'; store.persistProspectSearch(search); }
}
